server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/eureka/,http://localhost:8004/eureka/
  instance:
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
spring:
  application:
    name: order
  redis:
    host: 192.168.0.103
    port: 7001
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  rabbitmq:
    host: 192.168.97.115
    port: 5672
    username: xsf
    password: xsf
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
