server:
  port: 8005
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/eureka/,http://localhost:8004/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
spring:
  application:
    name: product

